# Generated by Django 5.2.6 on 2025-10-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
    ]
